import { ReactNode } from "react";
import type { Metadata } from "next";

import loadSerializableQuery from "@/relay/loadSerializableQuery";
import SidebarQueryNode, {
  SidebarQuery,
} from "@/__generated__/SidebarQuery.graphql";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { RelayProvider } from "@/relay/RelayProvider";
import "./reset.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  // Prepare the sidebar query
  const preloadedSidebarQuery = await loadSerializableQuery<
    typeof SidebarQueryNode,
    SidebarQuery
  >(SidebarQueryNode.params, {});

  return (
    <html>
      <head>
        <title>Relay Newsfeed app</title>
      </head>
      <RelayProvider>
        <body>
          <div className="app">
            {children}
            <Sidebar preloadedQuery={preloadedSidebarQuery} />
          </div>
        </body>
      </RelayProvider>
    </html>
  );
};

export default RootLayout;

export const revalidate = 0;
